# ip: "127.0.0.1"   # sim
ip: "10.201.2.179"   # real robot

left_upper_corner: [598.0,    478.]     # x, y in millimeters
right_down_corner: [602.0,  481.1]   # x, y in millimeters
safe_hight: 319.  # in millimeters
# min_hight: 0.01
sensor_hight: 317.9
max_sensor_depth: 0.4
minimal_possible_hight: 317.5
# for 1 point touching first minimum is at 0.0002 мм
sensor_depth_points: 16
time_to_measure: 0.8  # seconds
time_to_sleep: 0.2

sensor_id: null

# working_freq: 100   # Hz

speed: [0.3, 0.03]   ## maximal speed and acceleration

grid:
  steps: [0.2, 1]   # steps in millimeters

power_meter_address: 'USB0::4883::32888::P0006292::0::INSTR'
arduino_address: '/dev/ttyACM0'