ip: "127.0.0.1"   # sim
# ip: "10.201.2.179"   # real robot

left_upper_corner: [100.0,    100.]     # x, y in millimeters
right_down_corner: [300.0,  200.]   # x, y in millimeters

horisontal_area: [0, -1]  ## along the fiber, x' coord
vertical_area: [-1, 1]  ## around the fiber, y' coord
# horisontal_area: [5, -5]

safe_hight: 319.  # in millimeters
# min_hight: 0.01
sensor_hight: 317.9
max_sensor_depth: 0.4
minimal_possible_hight: 317.5
# for 1 point touching first minimum is at 0.0002 мм
sensor_depth_points: 2
time_to_measure: 0.8  # seconds
time_to_sleep: 0.2

sensor_id: null

# working_freq: 100   # Hz

speed: [0.3, 0.03]   ## maximal speed and acceleration

grid:
  steps: [40, 1]   # steps in millimeters

sensor_angle: -45  # angle between robot and sensor axes
power_meter_address: 'USB0::4883::32888::P0006292::0::INSTR'
arduino_address: '/dev/ttyACM0'