# ip: "127.0.0.1"   # sim
ip: "10.201.2.179"   # real robot

left_upper_corner: [0.486, 0.331]     # x, y in meters
right_down_corner: [0.476, 0.298]    # x, y in meters
safe_hight: 0.2886  # in meters
# min_hight: 0.01
sensor_hight: 0.2882
max_sensor_depth: 0.0005
sensor_depth_points: 100
wait_time: 0.5  # seconds

# force: [0.2, 0.3, 0.4]    # downwards force in Newtons
# push_time: [1, 0.3, 0.3]    # seconds

# working_freq: 100   # Hz

speed: [0.3, 0.1]   ## maximal speed and acceleration

grid:
  steps: [0.001, 0.005]   # steps in meters

power_meter_address: 'USB0::4883::32888::P0006292::0::INSTR'
arduino_address: '/dev/ttyACM0'